export const IPC_CHANNELS = {
  dialogOpenFile: "slate:dialog:open-file",
  dialogOpenDirectory: "slate:dialog:open-directory",
  dialogSaveFile: "slate:dialog:save-file",
  fileReadText: "slate:file:read-text",
  fileWriteText: "slate:file:write-text",
  fileWriteBinary: "slate:file:write-binary",
  fileReadDirectory: "slate:file:read-directory",
  fileRenamePath: "slate:file:rename-path",
  fileDuplicate: "slate:file:duplicate",
  fileMoveToTrash: "slate:file:move-to-trash",
  fileReveal: "slate:file:reveal",
  fileCopyPathToClipboard: "slate:file:copy-path-to-clipboard",
  fileStat: "slate:file:stat",
  fileWatchStart: "slate:file-watch:start",
  fileWatchStop: "slate:file-watch:stop",
  fileWatchEvent: "slate:file-watch:event",
  projectsRead: "slate:projects:read",
  projectsWrite: "slate:projects:write",
  gitIsRepo: "slate:git:is-repo",
  gitRoot: "slate:git:root",
  gitStatus: "slate:git:status",
  gitLog: "slate:git:log",
  gitDiff: "slate:git:diff",
  gitCommit: "slate:git:commit",
  gitCheckoutFile: "slate:git:checkout-file",
} as const
